---
# Go installation variables https://go.dev/dl/
go_version: "1.25.5"
go_checksum: "sha256:9e9b755d63b36acf30c12a9a3fc379243714c1c6d3dd72861da637f336ebb35b"

# golangci-lint https://github.com/golangci/golangci-lint/releases
golangci_lint_version: "2.7.2"
golangci_lint_checksum: "sha256:ce46a1f1d890e7b667259f70bb236297f5cf8791a9b6b98b41b283d93b5b6e88"
