---
# Go installation variables https://go.dev/dl/
go_version: "1.25.7"
go_checksum: "sha256:178f2832820274b43e177d32f06a3ebb0129e427dd20a5e4c88df2c1763cf10a"

# golangci-lint https://github.com/golangci/golangci-lint/releases
golangci_lint_version: "2.7.2"
golangci_lint_checksum: "sha256:ce46a1f1d890e7b667259f70bb236297f5cf8791a9b6b98b41b283d93b5b6e88"

# gopls https://github.com/golang/tools/releases?q=gopls
gopls_version: "0.21.1"
