---
- name: Install stow
  become: true
  apt:
    state: latest
    name: stow

- name: Ensure folders exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.m2
    - ~/.m2/conf
    - ~/.m2/logging
    - ~/.local/mvnd

- name: Create symlinks into dotfiles
  command: stow --target ~/ maven
  args:
    chdir: ~/code/dotfiles

- name: Fetch latest release information
  uri:
    url: https://api.github.com/repos/apache/maven-mvnd/releases/latest
    return_content: true
  register: mvnd_release_json

- name: "Download/untar mvnd (version {{ mvnd_release_json.json.name }})"
  loop: "{{ mvnd_release_json.json.assets }}"
  when:
    - item.name is match("^.*linux-amd64.tar.gz$")
  unarchive:
    src: "{{ item.browser_download_url }}"
    dest: ~/.local/mvnd
    creates: ~/.local/mvnd/mvnd
    remote_src: yes
    keep_newer: yes
    extra_opts:
      - --strip=1
      - --show-stored-names
