---
- name: Install packages
  become: true
  apt:
    pkg:
      - git
      - zsh
      - stow
    state: latest

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh

- name: Create symlinks to zsh dotfiles
  command:
    argv:
      - stow
      - --dotfiles
      - --target
      - ~/
      - --restow
      - zsh
  args:
    chdir: ~/code/dotfiles

# https://github.com/junegunn/fzf#using-git
# the zsh completion expects it to be in ~/.fzf by default
# otherwise an FZF_BASE needs to be provided. Using FZF_BASE
# did not work with alacritty when launching it, even though
# the env var was present. When launching a subshell it dit work.
# Therefore, I am sticking to the default location.
- name: Clone fzf
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    depth: 1
    force: true
  register: fzf_changed

- name: Install fzf
  command:
    cmd: ./install --completion --key-bindings --update-rc --no-bash --no-fish
    chdir: ~/.fzf
  when: fzf_changed.before != fzf_changed.after

- name: Clone fzf-git.sh
  git:
    repo: https://github.com/junegunn/fzf-git.sh
    dest: ~/.fzf-git
    depth: 1
    force: true

- name: Ensure fzf-scripts folders exist
  file:
    path: ~/.fzf-scripts
    state: directory

- name: Create symlinks to fzf-scripts in dotfiles
  command:
    argv:
      - stow
      - --dotfiles
      - --target
      - ~/
      - --restow
      - --stow
      - fzf-scripts
  args:
    chdir: ~/code/dotfiles
