---
- hosts: localhost
  gather_facts: true
  roles:
    - { role: uv, tags: [uv] }
    - { role: base, tags: [base] }
    - { role: tmpfiles, tags: [tmpfiles] }
    - { role: backup, tags: [backup] }
    - { role: sway, tags: [sway] }
    - { role: waybar, tags: [waybar] }
    - { role: mako, tags: [mako] }
    - { role: solaar, tags: [solaar] }
    - { role: alacritty, tags: [alacritty] }
    - { role: ghostty, tags: [ghostty] }
    - { role: atuin, tags: [atuin] }
    - { role: zoxide, tags: [zoxide] }
    - { role: stow, tags: [stow] }
    - { role: zsh, tags: [zsh] }
    - { role: vim, tags: [vim] }
    - { role: tmux, tags: [tmux] }
    - { role: lang-java, tags: [java] }
    - { role: lang-go, tags: [go] }
    - { role: lang-sql, tags: [sql] }
    - { role: dhis2, tags: [dhis2] }
