- name: Install packages
  become: true
  apt:
    pkg:
      - tmux
      - stow # required for linking the config

- name: Create symlinks into dotfiles
  command: stow --target ~/ tmux
  args:
    chdir: ~/code/dotfiles
  changed_when: false  # command module always shows changed; stow is idempotent, failures still detected via exit code

- name: Ensure plugin folder exists
  file:
    path: ~/.tmux/plugins
    state: directory

- name: Clone tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    recursive: no
    force: true
